//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRACE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
        public int TermID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public int Number { get; set; }
        public string Section { get; set; }
        public string DataID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Term Term { get; set; }
    }
}
